krishnacook/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from . import settings

from recipes.views import (
	recipe_list
	)
from accounts.views import (login_view, logout_view)

if settings.DEBUG:
	import debug_toolbar
	
urlpatterns = [
	#url(r'^register/', register_view, name='register'),
	url(r'^login/', login_view, name='login'),
	url(r'^logout/', logout_view, name='logout'),
	url(r'^admin/', admin.site.urls),
	url(r'^ingredients/', include("ingredients.urls", namespace='ingredients')),
	url(r'^typeofingredient/', include("typeofingredient.urls", namespace='typeofingredient')),
	url(r'^recipes/', include("recipes.urls", namespace='recipes')),
	url(r'^events/', include("menu.urls", namespace='menus')),
	url(r'^tags/', include("tags.urls", namespace='tags')),
	url(r'^mixedmeasurements/', include("recipe_ingredient_measurements.urls", namespace='mixedmeasurements')),
	url(r'^singlemeasurements/', include("single_measurements.urls", namespace='singlemeasurements')),


	
	url(r'^api/ingredients/', include("ingredients.api.urls", namespace='ingredients-api')),
	url(r'^api/recipes/', include("recipes.api.urls", namespace='recipes-api')),

	url(r'^$', recipe_list, name='recipelist'),
]


urlpatterns = [
	url(r'^__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

menu/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
	menu_list,
	menu_update,
	menu_confirm,
	menu_delete,
	menu_detail,
	menu_detail2,
	menu_detail_ingredient,
	menu_report,
	menu_print,
	menuposition_confirm,
	menuposition_update,
	menuposition_delete,
	menu_total_ingredients,
	menu_recipe_formset_update,
	menu_ingredient_custom_list,
	menu_ingredient_custom_inlineformset_bulk_edit,
	menu_ingredient_custom_recipe_report,
	menu_default_ingredients,
	menu_default_recipes,
	menu_ingredient_custom_recipe_recipe,
	menu_ingredient_custom_recipe_ingredient,
	menu_testing,
	menu_testing2,
	menu_ingredient_default_inlineformset_bulk_edit,
	menu_ingredient_custom_clear_all_values,
	menu_ingredient_custom_sync_with_default
	)

urlpatterns = [
	url(r'^$', menu_list, name='list'),
	url(r'^(?P<slug>[\w-]+)/testing/$', menu_testing, name='testing'),

	url(r'^(?P<slug>[\w-]+)/testing2/$', menu_testing2, name='testing2'),

	url(r'^(?P<slug>[\w-]+)/edit/$', menu_update, name='update'),
	url(r'^(?P<slug>[\w-]+)/editbulk/$', menu_recipe_formset_update, name='updaterecipebulk'),
	
	url(r'^(?P<slug>[\w-]+)/default/detail/$', menu_detail, name='default_detail'),
	url(r'^(?P<slug>[\w-]+)/default/recipes/$', menu_default_recipes, name='default_recipes'),
	url(r'^(?P<slug>[\w-]+)/default/ingredients/$', menu_default_ingredients, name='default_ingredients'),
	url(r'^(?P<slug>[\w-]+)/default/bulkedit$', menu_ingredient_default_inlineformset_bulk_edit, name='defaultingredient_bulkedit'),

	url(r'^(?P<slug>[\w-]+)/detail2/$', menu_detail2, name='detail2'),
	url(r'^(?P<slug>[\w-]+)/detail/ingredient/$', menu_detail_ingredient, name='detail_ingredient'),
	url(r'^(?P<slug>[\w-]+)/report/$', menu_report, name='report'),
	url(r'^(?P<slug>[\w-]+)/print/$', menu_report, name='print'), #menus_report.html
	


	url(r'^(?P<slug>[\w-]+)/delete/$', menu_delete, name='delete'),
	url(r'^(?P<slug>[\w-]+)/confirm/$', menu_confirm, name='confirm'),
	


	url(r'^(?P<slug>[\w-]+)/customingredient/list$', menu_ingredient_custom_list, name='customingredient_list'),
	url(r'^(?P<slug>[\w-]+)/customingredient/bulkedit$', menu_ingredient_custom_inlineformset_bulk_edit, name='customingredient_bulkedit'),

	url(r'^(?P<slug>[\w-]+)/customingredient/clear$', menu_ingredient_custom_clear_all_values, name='customingredient_clear'),	
	url(r'^(?P<slug>[\w-]+)/customingredient/sync$', menu_ingredient_custom_sync_with_default, name='customingredient_sync'),

	url(r'^(?P<slug>[\w-]+)/custom/detail$', menu_ingredient_custom_recipe_report, name='custom_detail'),
	url(r'^(?P<slug>[\w-]+)/custom/recipes$', menu_ingredient_custom_recipe_recipe, name='custom_recipes'),
	url(r'^(?P<slug>[\w-]+)/custom/ingredients$', menu_ingredient_custom_recipe_ingredient, name='custom_ingredients'),

	url(r'^pos/(?P<slug>[\w-]+)/edit/$', menuposition_update, name='updatepos'),
	url(r'^pos/(?P<slug>[\w-]+)/delete/$', menuposition_delete, name='deletepos'),
	url(r'^pos/(?P<slug>[\w-]+)/confirm/$', menuposition_confirm, name='confirmpos'),

	url(r'^(?P<slug>[\w-]+)/total/$', menu_total_ingredients, name='total'),


]

templates/clear_custom_ingredient.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% load ingredient_quantity %}

{% block content %}

<p> Values cleared </p>
{% endblock content %}

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

templates/menus_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block detail_link %}
  <li><a href='{% url "menus:list" %}'>Events</a></li>
{% endblock %}

{% block content %}
<div class='container'>
<div class='col-xs-6 col-xs-offset-3'>
  <h1>Confirm Delete</h1>
				<p>Are you sure you want to delete: "{{ name }}"?</p>
				<a href='{{ instance.get_absolute_url_delete }}' class='btn btn-warning'>Delete</a>
				<a href='{{ instance.get_absolute_url_detail }}' class='btn btn-default'>Cancel</a>
			</form>
		</div>

	

		<hr/>
</div>
{% endblock content %}

templates/menus_detail_custom_and_default_ingredients.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block detail_link %}
  <li><a href='{% url "menus:list" %}'>Events</a></li>
  <li><a href='{{ instance.get_absolute_url_detail }}'>{{ instance.name }}</a></li>
{% endblock %}

{% load ingredient_quantity %}

{% block content %}


 <div class="container">
    <h3> List of Ingredients Required</h1>
    <b><a href='{{ instance.menu_ingredient_custom_inlineformset_bulk_edit }}'>Bulk Edit</a></b><br>
    
</div>

<div class="container-non-responsive simhat" style="margin-right: auto;margin-left: auto;;padding-left: 20px;padding-right: 20px;width: 3000px;">

    <div class="row" style="border-top:1.5px solid;">
        <div class="col-xs-2 simha" style="width:50px">S.No</div>
        <div class="col-xs-2 simha" style="width:300px">Ingredient</div>
        <div class="col-xs-2 simha" style="width:100px">Type of Ingr</div>
        <div class="col-xs-2 simha" style="width:1400px">
            <div class="row" style="width:1400px">
                <div class="col-xs-1" style="width:300px;"> S.No / Sq.No</div>
                <div class="col-xs-1" style="width:1100px">
                    <div class="row">
                        <div class="col-xs-1 simha2" style="width:80px;text-align:center">S.No / Sq.No</div>
                        <div class="col-xs-2 simha2" style="width:200px;text-align:left">Name</div>
                        <div class="col-xs-1 simha2" style="width:80px;text-align:right">Yeild Bulk Qty</div>
                        <div class="col-xs-1 simha2"  style="width:100px;text-align:left">Unit</div>
                        <div class="col-xs-1 simha" style="width:100px;text-align:center">factor</div>
                        <div class="col-xs-1 simha2" style="width:80px;text-align:right">Req Bulk Qty</div>
                        <div class="col-xs-1 simha2"  style="width:100px;text-align:left">Unit</div>
                        <div class="col-xs-1 simha2" style="width:80px;text-align:right">Req Basic Qty (kg/ltr/pcs)</div>
                        <div class="col-xs-1 simha2"  style="width:70px;text-align:left">Unit</div>
                        <div class="col-xs-1 simha2" style="width:90px;text-align:right">density factor</div>
                        <div class="col-xs-1 simha2" style="width:90px;text-align:right">cost quantity</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-1 simha2" style="width:90px;text-align:right">cost quantity</div>
        <div class="col-xs-1 simha2" style="width:110px;text-align:right">rate</div>
        <div class="col-xs-1 simha2" style="width:110px;text-align:right">cost</div>
        <div class="col-xs-2 simha" style="width:300px">Ingredient</div>
    </div>
    
    {% for ingredient in ingredients_dictinct %}
    <div class="row" style="border-top:1.5px solid;">
        <!-- Ingredient S.No -->
        <div class="col-xs-2 simha" style="width:50px">{{ forloop.counter }}</div>
        
        <!-- Ingredient Name -->
        <div class="col-xs-2 simha" style="width:300px">
            {{ ingredient.name }}
        </div>

        <!-- Type of Ingredient -->
        <div class="col-xs-2 simha" style="width:100px">{{ ingredient.typeofingredient}}</div>

        <!-- MenuPositions of each Ingredient -->
        <div class="col-xs-2 simha" style="width:1400px">
        
        <!-- get the menupositions in which the ingredient it used -->
        {% ingredient_menu_recipes  ingredient instance as menupositions %}
        {% for menuposition in menupositions %} 
            <div class="row" style="width:1400px">

                <div class="col-xs-1" style="width:300px;">
                {% if menuposition.name == menuposition.menurecipe.name %}
                    {{ forloop.counter }}({{ menuposition.id }}). {{ menuposition.name }}
                {% else %}
                     {{ forloop.counter }}({{ menuposition.id }}). {{ menuposition.name }}({{ menuposition.menurecipe.name }})
                {% endif %}
                </div>

                <div class="col-xs-1" style="width:1100px">
                    <!-- get the recipeposition in which the ingredient is used -->
                    {% ingredient_recipepositions ingredient menuposition as recipepositions %}
                    {% for recipeposition in recipepositions %}
                    <div class="row">
                      
                        
                        <!-- S.No -->
                        <div class="col-xs-1 simha2" style="width:80px;text-align:center">{{ forloop.counter }}({{ recipeposition.sequence_number }})</div>
                        
                        <!-- Ingredient Name(Notes) -->
                        <div class="col-xs-2 simha2" style="width:200px;text-align:left">
                        {% if recipeposition.cooking_notes != "" %}
                        <b>{{ recipeposition.name }}</b><i> ({{ recipeposition.cooking_notes }})</i>
                        {% else %}
                        <b>{{ recipeposition.name }}</b>
                        {% endif %}
                        </div>
                        
                        {% mvwith menuposition.menurecipe_factor_of_recipe_quantity_wrt_lt_kg_pcs as factor%}
                        {% list_factor_qty_unit_bulk_and_kg_ltr_pcs_list_recipeposition recipeposition factor as rcplist%}
                        
                        <!-- Bulk Qty -->
                        <div class="col-xs-1 simha2" style="width:80px;text-align:right">
                            {% for var in rcplist %}
                                {% if var.unit_exists == 1 %}
                                    {{ var.bulk.quantity|floatformat:2 }}<br>
                                {% endif %}
                            {% endfor %}
                        </div>
                        
                        <!-- Unit -->
                        <div class="col-xs-1 simha2"  style="width:100px;text-align:left">
                            {% for var in rcplist %}
                                {% if var.unit_exists == 1 %}
                                    {{ var.bulk.unit }}<br>
                                {% endif %}
                            {% endfor %}
                        </div>
                        
                        <!-- factor -->
                        
                        <div class="col-xs-1 simha" style="width:100px;text-align:center"> x {{ factor|floatformat:2  }}</div>
                        
                        <!--factored Bulk Qty -->
                        <div class="col-xs-1 simha2" style="width:80px;text-align:right">
                            {% for var in rcplist %}
                                {% if var.unit_exists == 1 %}
                                    {{ var.bulk_fact.quantity|floatformat:2 }}<br>
                                {% endif %}
                            {% endfor %}
                        </div>
                        
                        <!-- Unit -->
                        <div class="col-xs-1 simha2"  style="width:100px;text-align:left">
                            {% for var in rcplist %}
                                {% if var.unit_exists == 1 %}
                                    {{ var.bulk_fact.unit }}<br>
                                {% endif %}
                            {% endfor %}
                        </div>


                        <!-- factored Basic Qty -->
                        <div class="col-xs-1 simha2" style="width:80px;text-align:right">
                            {% for var in rcplist %}
                                {% if var.unit_exists == 1 %}
                                    {{ var.basic_fact.quantity|floatformat:2 }}<br>
                                {% endif %}
                            {% endfor %}
                        </div>
                        
                         <!-- Basic Unit -->
                        <div class="col-xs-1 simha2"  style="width:70px;text-align:left">
                            {% for var in rcplist %}
                                {% if var.unit_exists == 1 %}
                                    {{ var.basic_fact.unit }}<br>
                                {% endif %}
                            {% endfor %}
                        </div>

                        {% dict_factor_density_cost_custom_ing_recipeposition recipeposition instance factor as rcpdict %}

                        <!-- density factor -->
                        <div class="col-xs-1 simha2" style="width:90px;text-align:right">
                            {{ rcpdict.inverse }}{{ rcpdict.density_factor }} {{ rcpdict.density_unit }}
                        </div>

                        <!-- cost quantity -->
                        <div class="col-xs-1 simha2" style="width:90px;text-align:right">
                            {{ rcpdict.cost_quantity_factor|floatformat:2 }} {{ rcpdict.cost_unit }}
                        </div>

                    </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>

        {% ingredient_qty_rate_cost_custom_ingredient ingredient instance as ingr_prop %}
        <!-- cost quantity -->
        <div class="col-xs-1 simha2" style="width:90px;text-align:right">
            {{ ingr_prop.cost_quantity|floatformat:2 }} {{ ingredient.munit }}
        </div>

         <!-- rate -->
        <div class="col-xs-1 simha2" style="width:110px;text-align:right">
            Rs {{ ingr_prop.rate|floatformat:2 }}/{{ ingredient.munit }}
        </div>

        <!-- cost -->
        <div class="col-xs-1 simha2" style="width:110px;text-align:right">
           Rs {{ ingr_prop.cost|floatformat:2 }}
        </div>

        <!-- Ingredient Name -->
        <div class="col-xs-2 simha" style="width:300px">
            {{ ingredient.name }}
        </div>


    </div>
{% endfor %}
</div>

{% endblock content %}

templates/menus_list_backup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load ingredient_quantity %}

{% block detail_link %}
  <li><a href='{% url "menus:list" %}'>Events</a></li>
{% endblock %}

{% block content %}


<div class='container'>
    <div class="row">
            <div class="col-xs-5">
            <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
            {{ form|crispy }}
            <div class="col-xs-2"><input type='submit' class='btn btn-default' value='Create' /></div>
            </form>
        </div>
    </div>

    {% include "messages_display.html" %}
</div>
<hr>

<div class="container-non-responsive simhat" style="margin-right: auto;margin-left: auto;padding-left: 20px;padding-right: 20px;width: 5000px;">

    <hr/>
    <div class="row simhaf">
        <div class="col-xs-2" style="width:50px"><b>S.No</b></div>
        <div class="col-xs-2" style="width:50px"><b>Id</b></div>
        <div class="col-xs-1" style="width:150px"><b>Name</b></div>
        <div class="col-xs-1" style="width:400px"><b>Recipes</b></div>
        <div class="col-xs-1" style="width:170px"><b>Avg No: People</b></div>
        <div class="col-xs-1" style="width:200px"><b>Total Cost</b></div>
        <div class="col-xs-1" style="width:170px"><b>Avg Cost per Person</b></div>
        <div class="col-xs-1" style="width:170px"><b>Total Cost </b></div>
        <div class="col-xs-1" style="width:100px"><b>Up Date</b></div>
        <div class="col-xs-1" style="width:100px"><b>Cr Date</b></div>
        <div class="col-xs-1" style="width:100px"><b>Edit</b></div>
        <div class="col-xs-1" style="width:100px"><b>Delete</b></div>
        <div class="col-xs-1" style="width:100px"><b>Slug</b></div>
    </div>
    <hr/>

    {% for instance in object_list %}
    <div class="row">
            <div class="col-xs-2" style="width:50px">{{ forloop.counter }}</div>
            <div class="col-xs-2" style="width:50px"><b>{{ instance.id }}</b></div>
            <div class="col-xs-1" style="width:150px"><b><a href='{{ instance.get_absolute_url_detail }}'>{{ instance.name }}</a></b><b><a href='{{ instance.get_absolute_url_menu_update_inline_bulk_recipes }}'>/Edit/</a><a href='{{ instance.get_absolute_url_customingredient }}'>Custom List</a></b><b><a href='{{ instance.menu_ingredient_custom_inlineformset_bulk_edit }}'>/Bulk Edit</a></b><b><a href='{{ instance.menu_ingredient_custom_recipe_report }}'>/Default_custom_Edit</a></b></div>
            <div class="col-xs-1 simha" style="width:400px;">
            No of recipes - {{ instance.get_number_of_recipes }} <br>
            <ul>
            {% for obj in instance.menu_positions.all %}
                <li>
                    {{ obj.persons|floatformat:0 }} p 
                    :: {{ obj.get_person_consumption_dict_single.qty|floatformat:0 }} {{ obj.get_person_consumption_dict_single.unit  }}/p 
                    :: {{ obj.menurecipe.name }} 
                    :: Rs {{ obj.cost_per_recipe_for_the_consumption_unit_class.cost|floatformat:4 }} / {{ obj.cost_per_recipe_for_the_consumption_unit_class.unit }} <br>
                    Rs {{ obj.total_cost_for_total_quantity_kg_lt_pc_dict_single.qty|floatformat:2  }}  for
                    {{ obj.total_quantity_in_kg_lt_pcs_dict_single.qty|floatformat:0  }} {{ obj.total_quantity_in_kg_lt_pcs_dict_single.unit }} 
                    :: Rs {{ obj.total_cost_per_person_kg_lt_pc_dict_single.qty|floatformat:4 }}/p
                </li>
            {% endfor %}
            </ul>
            </div>
            {% mvwith instance.average_number_of_people_dict as menu_prop %}
            <!-- Average no: of people -->
            <div class="col-xs-1 simha" style="width:170px;">
            ({% for obj in instance.menu_positions.all %}
            {{ obj.persons|floatformat:0 }} p 

            {% if not forloop.last %}
            + <br>
            {% endif %} 
            {% endfor %}) / {{ menu_prop.countr }}<br> = {{ menu_prop.avgp|floatformat:0 }}
            </div>
            <!-- Total Cost -->
            <div class="col-xs-1 simha" style="width:200px;">
            {% for obj in instance.menu_positions.all %}
            Rs {{ obj.total_cost_for_total_quantity_kg_lt_pc_dict_single.qty|floatformat:2 }} for  {{ obj.total_quantity_in_kg_lt_pcs_dict_single.qty|floatformat:0  }} {{ obj.total_quantity_in_kg_lt_pcs_dict_single.unit }}

            {% if not forloop.last %}
            + <br>
            {% endif %} 
            {% endfor %} <br>= 

            Rs {{ menu_prop.total_cost|floatformat:2 }} </div>
            <!-- average cost per person -->
            <div class="col-xs-1 simha" style="width:170px;">
            {{ menu_prop.total_cost|floatformat:2 }} / {{ menu_prop.avgp|floatformat:2 }} <br>= Rs {{ menu_prop.avg_cost_per_person|floatformat:2 }}/p
            </div>
            <!-- total coast per person -->
            <div class="col-xs-1 simha" style="width:170px;">
            {% for obj in instance.menu_positions.all %}
                 Rs {{ obj.total_cost_per_person_kg_lt_pc_dict_single.qty|floatformat:2 }}/p 
                
                 {% if not forloop.last %}
                 +<br>
                 {% endif %} 
                 
             {% endfor %}
              <br>=  Rs {{ instance.cost_per_person_add_independent|floatformat:1 }}/p
            </div>
            <div class="col-xs-1 simha" style="width:100px;">{{ instance.updated }}</div>
            <div class="col-xs-1 simha" style="width:100px;">{{ instance.timestamp }}</div>
            <div class="col-xs-1 simha" style="width:100px;"><b><a href='{{ instance.get_absolute_url_update }}'>Edit</a></b></div>
            <div class="col-xs-1 simha" style="width:100px;"><b><a href='{{ instance.get_absolute_url_confirm }}'>Delete</a></b></div>
            <div class="col-xs-1 simha" style="width:100px">{{ instance.slug }}</div>
    </div>

<hr/>
{% endfor %}
</div>
<div class="container">
<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock content %}

templates/menus_total_ingredients.html
{% extends "base.html" %}

{% block detail_link %}
  <li><a href='{% url "menus:list" %}'>Events</a></li>
{% endblock %}

{% block content %}
<div class='container'>
<p> Total Ingredients Required</p>
		<hr/>
		<div class="row">
		<div class="col-xs-2">Ingredient</div>
		<div class="col-xs-2">Type</div>
		<div class="col-xs-1">M Unit</div>
		<div class="col-xs-2">Total Quantity</div>
		</div>
		<hr/>
	{% for recipedetail in menurecipe_list %}
		<div class="row">
		<div class="col-xs-2">{{ recipedetail.ingredientname }}</div>
		<div class="col-xs-2">{{ recipedetail.typeofingredient__name }}</div>
		<div class="col-xs-1">{{ recipedetail.munit }}</div>
		<div class="col-xs-2">{{ recipedetail.total_quantity_ingredient }}</div>
		</div>
		<hr/>
	{% endfor %}
</div>
{% endblock content %}


<!-- <hr/>
<div class="row">
    <div class="col-xs-1"><b>Name</b></div>
    <div class="col-xs-1"><b>Slug</b></div>
    <div class="col-xs-2"><b>Up Date</b></div>
    <div class="col-xs-2"><b>Cr Date</b></div>
    <div class="col-xs-1"><b>Detail</b></div>
    <div class="col-xs-1"><b>Delete</b></div>
</div>
<hr/>

{% for obj in object_list %}
<div class="row">
    <div class="col-xs-1">{{ obj.name }}</div>
    <div class="col-xs-1">{{ obj.slug }}</div>
    <div class="col-xs-2">{{ obj.updated }}</div>
    <div class="col-xs-2">{{ obj.timestamp }}</div>
    <div class="col-xs-1"><b><a href='{{ obj.get_absolute_url_detail }}'>Detail</a></b></div>
    <div class="col-xs-1"><b><a href='{{ obj.get_absolute_url_confirm }}'>Delete</a></b></div>
</div>
<hr/>
{% endfor %} -->

templates/typeofingredient_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block detail_link %}
  <li><a href='{% url "typeofingredient:list" %}'>Ingredient Type</a></li>
{% endblock %}

{% block content %}
<div class='container'>
<div class='col-xs-6 col-xs-offset-3'>
  <h1>Confirm Delete</h1>
				<p>Are you sure you want to delete: "{{ instance.name }}"?</p>
				<a href='{{ instance.get_absolute_url_delete }}' class='btn btn-warning'>Delete</a>
				<a href='{% url "ingredients:list" %}' class='btn btn-default'>Cancel</a>
			</form>
		</div>

	

		<hr/>
</div>
{% endblock content %}

templates/typeofingredient_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block detail_link %}
  <li><a href='{% url "typeofingredient:list" %}'>Ingredient Type</a></li>
{% endblock %}

{% block content %}
<div class='container'>
<div class="row">
<div class="col-xs-5">
<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<div class="col-xs-2"><input type='submit' class='btn btn-default' value='Create' /></div>
</form>
</div>
</div>

<hr/>
<div class="row">
    <div class="col-xs-1" style="width:50px"><b>S.No</b></div>
    <div class="col-xs-1" style="width:50px"><b>Id</b></div>
    <div class="col-xs-2"><b>Name</b></div>
    <div class="col-xs-2"><b>Slug</b></div>
    <div class="col-xs-2"><b>Up Date</b></div>
    <div class="col-xs-2"><b>Cr Date</b></div>
    <div class="col-xs-1"><b>Detail</b></div>
    <div class="col-xs-1"><b>Delete</b></div>
</div>
<hr/>

{% for obj in object_list %}
<div class="row">
    <div class="col-xs-1 simha" style="width:50px">{{ forloop.counter }}</div>
    <div class="col-xs-1 simha" style="width:50px">{{ obj.id }}</div>
    <div class="col-xs-2">{{ obj.name }}</div>
    <div class="col-xs-2">{{ obj.slug }}</div>
    <div class="col-xs-2">{{ obj.updated }}</div>
    <div class="col-xs-2">{{ obj.timestamp }}</div>
    <div class="col-xs-1"><b><a href='{{ obj.get_absolute_url_update }}'>Detail</a></b></div>
    <div class="col-xs-1"><b><a href='{{ obj.get_absolute_url_confirm }}'>Delete</a></b></div>
</div>
<hr/>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?{{ page_request_var }}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{ page_request_var }}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock content %}